export SPACESHIP_PACKAGE_SHOW=false

# geometry theme config
export GEOMETRY_PROMPT_PLUGINS=(virtualenv git node)

export GEOMETRY_GIT_SYMBOL_REBASE="\uE0A0"
export GEOMETRY_GIT_SYMBOL_STASHES=x
export GEOMETRY_GIT_COLOR_STASHES=blue
export GEOMETRY_GIT_GREP=ack
export GEOMETRY_GIT_NO_COMMITS_MESSAGE="no commits"
export GEOMETRY_GIT_TIME_DETAILED=true

export GEOMETRY_SYMBOL_GIT_DIRTY=
export GEOMETRY_SYMBOL_GIT_CLEAN=
